<?php
/**
 * Magebuzz 2015
 */
?>
<div class="right-fixed sidebar">
<div class="right-content">
    <div class="block block-promotion">
        <div class="block-content">
            <a title="<?php echo $this->__('500+ New'); ?>" href="#">
                <img alt="<?php echo $this->__('500+ New'); ?>"
                     src="<?php echo $this->getSkinUrl('images/500New.png'); ?>"/>
            </a>
        </div>
        <div class="block-desc">
            <p><?php echo $this->__('Demo example content'); ?></p>
            <a href="#" title="<?php echo $this->__('Test Links'); ?>"><?php echo $this->__('Test Links'); ?></a>
            <a class="btn-link">Link button</a>
        </div>
    </div>
</div>
</div>
