<div class="block block-cart" id="flexiblenavigationmenu_cart_sidebar" style="display:none;padding:0px;margin:0px;">
    <?php $_cartQty = $this->getSummaryCount() ?>
    <div class="block-title">
        <strong><span><?php echo $this->__('My jkn kl') ?></span></strong>
    </div>
    <div class="block-content">
    <?php if ($_cartQty>0): ?>
        <div class="summary">
            <?php if ($_cartQty==1): ?>
                <p class="amount"><?php echo $this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart')) ?></p>
            <?php else: ?>
                <p class="amount"><?php echo $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?></p>
            <?php endif ?>
            <p class="subtotal">
                <?php if ($this->canApplyMsrp()): ?>
                    <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                <?php else: ?>
                    <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                        <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                    <?php endif; ?>
                <?php endif; ?>
            </p>
        </div>
    <?php endif ?>
    <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
    <div class="actions">
        <?php echo $this->getChildHtml('extra_actions') ?>
        <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
    </div>
    <?php endif ?>
    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>
        <p class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></p>
        <ol id="cart-top" class="mini-products-list">
        <?php foreach($_items as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('cart-top', 'none-recursive')</script>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <?php endif ?>
    </div>
</div>


<script>                    
    Event.observe(window, 'resize', locateCart);
    Event.observe(window, 'load', locateCart);

    function locateCart() {
        <?php if ($this->getIsRWD()) { ?>
        $$("#nav .nav-primary > .nav-<?php echo $this->getLevelCounters()?>").each(function(elmt) {
        <?php } else {?>
        $$("#nav > .nav-<?php echo $this->getLevelCounters()?>").each(function(elmt) {
        <?php } ?>
            my_div = $('flexiblenavigationmenu_cart_sidebar');
            elmt.up().up().appendChild(my_div);
            my_div.hide();

            var left = elmt.cumulativeOffset().left;
            my_div.setStyle({
                position: 'absolute',
                width: '200px',
                left: Element.positionedOffset(elmt).left + 'px',
                background: '#FBFBFB',
                border: 'solid 1px #cccccc',
                padding: '5px'
            });

            my_div.style.zIndex = 1000;
            my_div.style.textAlign = 'left';
            elmt.observe('mouseover', function() {
                $('flexiblenavigationmenu_cart_sidebar').show();
            });
            elmt.observe('mouseout', function() {
                $('flexiblenavigationmenu_cart_sidebar').hide();
            });
            my_div.observe('mouseover', function() {
                $('flexiblenavigationmenu_cart_sidebar').show();
            });
            my_div.observe('mouseout', function() {
                $('flexiblenavigationmenu_cart_sidebar').hide();
            });
            
        });
        decorateList('flexiblenavigationmenu_cart_sidebar', 'none-recursive');
    }

</script>
