DELETE FROM core_config_data WHERE `path` LIKE '%unirgy%';
DELETE FROM core_config_data WHERE `path` LIKE '%udropship%';
DELETE FROM core_config_data WHERE `path` LIKE '%udsplit%';
DELETE FROM core_config_data WHERE `path` LIKE '%umicrosite%';
DELETE FROM core_config_data WHERE `path` LIKE '%upadaptive%';
DELETE FROM core_config_data WHERE `path` LIKE '%udtiership%';
DELETE FROM core_config_data WHERE `path` LIKE '%udqa%';
DELETE FROM core_config_data WHERE `path` LIKE '%udmember%';
DELETE FROM core_config_data WHERE `path` LIKE '%udprod%';
DELETE FROM core_config_data WHERE `path` LIKE '%customstates%';
DELETE FROM eav_attribute WHERE attribute_code = 'udropship_vendor';
DELETE FROM eav_attribute WHERE attribute_code = 'vendor_landing_page';
DELETE FROM eav_attribute WHERE attribute_code = 'udropship_calculate_rates';
DELETE FROM eav_attribute WHERE attribute_code = 'udtiership_use_custom';
DELETE FROM eav_attribute WHERE attribute_code = 'udtiership_rates';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_attributes_changed';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_cfg_simples_added';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_cfg_simples_removed';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_pending_notified';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_approved_notified';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_fix_notified';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_pending_admin_notified';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_approved_admin_notified';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_fix_admin_notified';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_pending_notify';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_approved_notify';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_fix_notify';
DELETE FROM eav_attribute WHERE attribute_code = 'udprod_fix_description';
DELETE FROM admin_rule WHERE resource_id LIKE '%udropship%';
DELETE FROM admin_rule WHERE resource_id LIKE '%udqa%';
DELETE FROM admin_rule WHERE resource_id LIKE '%uvimport%';
DELETE FROM admin_rule WHERE resource_id LIKE '%udmember%';
DELETE FROM admin_rule WHERE resource_id LIKE '%udprod%';
DELETE FROM admin_rule WHERE resource_id LIKE '%usimpleup%';
DELETE FROM permission_block WHERE block_name = 'customstates/vendors';
DELETE FROM amasty_amfpc_url WHERE url LIKE '%udropship%';
DELETE FROM core_resource WHERE code = 'udmember_setup';
DELETE FROM core_resource WHERE code = 'udminamount_setup';
DELETE FROM core_resource WHERE code = 'udmspro_setup';
DELETE FROM core_resource WHERE code = 'udpayout_setup';
DELETE FROM core_resource WHERE code = 'udprod_setup';
DELETE FROM core_resource WHERE code = 'udpromo_setup';
DELETE FROM core_resource WHERE code = 'udqa_setup';
DELETE FROM core_resource WHERE code = 'udropship_setup';
DELETE FROM core_resource WHERE code = 'udshipclass_setup';
DELETE FROM core_resource WHERE code = 'udsplit_setup';
DELETE FROM core_resource WHERE code = 'udtax_setup';
DELETE FROM core_resource WHERE code = 'udtiercom_setup';
DELETE FROM core_resource WHERE code = 'udtiership_setup';
DELETE FROM core_resource WHERE code = 'udvacation_setup';
DELETE FROM core_resource WHERE code = 'umicrosite_setup';
DELETE FROM core_resource WHERE code = 'upadaptive_setup';
DELETE FROM core_resource WHERE code = 'usimplelic_setup';
DELETE FROM core_resource WHERE code = 'usimpleup_setup';
DELETE FROM core_resource WHERE code = 'uvimport_setup';
DELETE FROM core_resource WHERE code = 'customstates_setup';
DELETE FROM sales_flat_quote_item_option WHERE code LIKE '%udropship%';
DROP TABLE IF EXISTS usimplelic_license;
DROP TABLE IF EXISTS usimpleup_module;
DROP TABLE IF EXISTS udtiership_vendor_simple_cond_rates;
DROP TABLE IF EXISTS udtiership_vendor_simple_rates;
DROP TABLE IF EXISTS udtiership_vendor_rates;
DROP TABLE IF EXISTS udmember_membership;
DROP TABLE IF EXISTS udqa_question;
DROP TABLE IF EXISTS udropship_shipping_method;
DROP TABLE IF EXISTS udropship_shipping_title;
DROP TABLE IF EXISTS udropship_shipping_website;
DROP TABLE IF EXISTS udropship_payout_adjustment;
DROP TABLE IF EXISTS udropship_payout_row;
DROP TABLE IF EXISTS udropship_payout;
DROP TABLE IF EXISTS udropship_label_batch;
DROP TABLE IF EXISTS udropship_label_shipment;
DROP TABLE IF EXISTS udtiership_product_rates;
DROP TABLE IF EXISTS udtiership_rates;
DROP TABLE IF EXISTS udtiership_simple_cond_rates;
DROP TABLE IF EXISTS udtiership_simple_rates;
DROP TABLE IF EXISTS udtiership_vendor_rates;
DROP TABLE IF EXISTS udshipclass_customer_row;
DROP TABLE IF EXISTS udshipclass_vendor_row;
DROP TABLE IF EXISTS udropship_vendor_statement_adjustment;
DROP TABLE IF EXISTS udropship_vendor_statement_refund_row;
DROP TABLE IF EXISTS udropship_vendor_statement_row;
DROP TABLE IF EXISTS udropship_vendor_shipping;
DROP TABLE IF EXISTS udropship_vendor_statement;
DROP TABLE IF EXISTS udropship_vendor_product_assoc;
DROP TABLE IF EXISTS udropship_vendor_registration;
DROP TABLE IF EXISTS udropship_vendor_lowstock;
DROP TABLE IF EXISTS udropship_vendor_product;
DROP TABLE IF EXISTS udshipclass_vendor;
DROP TABLE IF EXISTS udshipclass_customer;
DROP TABLE IF EXISTS udtiership_delivery_type;
DROP TABLE IF EXISTS udropship_shipping;
ALTER TABLE admin_user DROP FOREIGN KEY FK_ADMIN_USER_VENDOR;
ALTER TABLE sales_flat_shipment DROP FOREIGN KEY udropship_vendor;
ALTER TABLE sales_flat_shipment DROP FOREIGN KEY udropship_shipcheck;
DROP TABLE IF EXISTS udropship_vendor;
ALTER TABLE sales_flat_shipment_grid DROP COLUMN udropship_payout_status;
ALTER TABLE sales_flat_shipment_comment DROP COLUMN udropship_status;
ALTER TABLE sales_flat_shipment DROP COLUMN udropship_status;
ALTER TABLE sales_flat_shipment DROP COLUMN udropship_vendor_order_id;
ALTER TABLE sales_flat_shipment DROP COLUMN udropship_payout_status;
ALTER TABLE sales_flat_quote_shipping_rate DROP COLUMN udropship_vendor;
ALTER TABLE sales_flat_quote_item DROP COLUMN udropship_vendor;
ALTER TABLE sales_flat_quote_address_item DROP COLUMN udropship_vendor;
ALTER TABLE sales_flat_quote_address DROP COLUMN udropship_shipping_details;
ALTER TABLE sales_flat_quote DROP COLUMN udropship_shipping_details;
ALTER TABLE sales_flat_order_item DROP COLUMN udropship_vendor;
ALTER TABLE sales_flat_order_item DROP COLUMN ud_base_tax_amount;
ALTER TABLE sales_flat_order_item DROP COLUMN ud_base_hidden_tax_amount;
ALTER TABLE sales_flat_order_item DROP COLUMN ud_base_discount_amount;
ALTER TABLE sales_flat_order_item DROP COLUMN ud_base_row_total;
ALTER TABLE sales_flat_order_item DROP COLUMN ud_row_total;
ALTER TABLE sales_flat_order DROP COLUMN udropship_status;
ALTER TABLE sales_flat_order DROP COLUMN udropship_shipping_details;
ALTER TABLE sales_flat_order DROP COLUMN ud_amount_fields;
ALTER TABLE sales_flat_order DROP COLUMN is_udmember;
ALTER TABLE salesrule DROP COLUMN udropship_vendor;
ALTER TABLE quotation DROP COLUMN vendor_id;
ALTER TABLE admin_user DROP COLUMN udropship_vendor;