DROP TABLE IF EXISTS amasty_amfpc_url;
DROP TABLE IF EXISTS amasty_amfpc_stats;
DROP TABLE IF EXISTS amasty_amfpccrawler_queue;
DROP TABLE IF EXISTS amasty_amfpccrawler_log;
DROP TABLE IF EXISTS amasty_amoptimization_task;
DELETE FROM core_config_data WHERE `path` LIKE '%amoptimization%';
DELETE FROM core_resource WHERE code = 'amoptimization_setup';
DELETE FROM admin_rule WHERE resource_id LIKE '%amnumber%';
DELETE FROM core_config_data WHERE `path` LIKE '%amnumber%';
DELETE FROM admin_rule WHERE resource_id LIKE '%amfpccrawler%';
DELETE FROM core_config_data WHERE `path` LIKE '%amfpccrawler%';
DELETE FROM core_resource WHERE code = 'amfpccrawler_setup';
DELETE FROM admin_rule WHERE resource_id LIKE '%amfpc%';
DELETE FROM core_config_data WHERE `path` LIKE '%amfpc%';
DELETE FROM core_resource WHERE code = 'amfpc_setup';
DELETE FROM core_cache_option WHERE code = 'amfpc';
DELETE FROM core_cache_tag WHERE tag LIKE '%amfpc%';
DELETE FROM core_config_data WHERE `path` LIKE '%Amasty_Fpc%';
DELETE FROM core_config_data WHERE `path` LIKE '%Amasty_Fpccrawler%';
DELETE FROM core_config_data WHERE `path` LIKE '%Amasty_Optimization%';
DELETE FROM core_config_data WHERE `path` LIKE '%Amasty_Number%';