DELETE FROM core_config_data WHERE `path` LIKE '%Magebuzz_Conversation%';
DELETE FROM core_config_data WHERE `path` LIKE '%Magebuzz_Ajaxcart%';
DELETE FROM core_config_data WHERE `path` LIKE '%Magebuzz_Custom%';
DELETE FROM core_config_data WHERE `path` LIKE '%Magebuzz_Dealerlocator%';
DELETE FROM core_config_data WHERE `path` LIKE '%Magebuzz_Faq%';
DELETE FROM admin_rule WHERE resource_id LIKE '%conversation%';
DELETE FROM core_config_data WHERE `path` LIKE '%conversation%';
DELETE FROM core_resource WHERE code = 'conversation_setup';
DELETE FROM admin_rule WHERE resource_id LIKE '%ajaxcart%';
DELETE FROM core_config_data WHERE `path` LIKE '%ajaxcart%';
DELETE FROM core_resource WHERE code = 'ajaxcart_setup';
DELETE FROM core_resource WHERE code = 'custom_setup';
DELETE FROM core_config_data WHERE `path` LIKE '%dealerlocator%';
DELETE FROM core_resource WHERE code = 'dealerlocator_setup';
DELETE FROM core_config_data WHERE `path` LIKE '%faq%';
DELETE FROM core_resource WHERE code = 'faq_setup';
DROP TABLE IF EXISTS mb_conversation_store;
DROP TABLE IF EXISTS mb_conversation_attachment;
DROP TABLE IF EXISTS mb_conversation_message;
DROP TABLE IF EXISTS mb_conversation;
DROP TABLE IF EXISTS faq_category_item;
DROP TABLE IF EXISTS faq_category_store;
DROP TABLE IF EXISTS faq_category;
DROP TABLE IF EXISTS faq_store;
DROP TABLE IF EXISTS faq;
DELETE FROM `eav_attribute` WHERE attribute_code ='thumbnail' AND entity_type_id=3;