<?php
/*
NOTICE OF LICENSE

This source file is subject to the SafeMageEULA that is bundled with this package in the file LICENSE.txt.

It is also available at this URL: https://www.safemage.com/LICENSE_EULA.txt

Copyright (c)  SafeMage (https://www.safemage.com/)
*/
?>
<?php

?>
<script type="text/javascript">
Event.observe(window, 'load', function() {
    if (!safemageDetectProductActiveTab()) {
        safemageClickProductTab();
    }
});
function safemageDetectProductActiveTab() {
    var activeTabs = [];
    $$('ul#product_info_tabs li a.active').each(function(i){
        activeTabs.push(i);
    });
    var res = (activeTabs.length > 0);
    return res;
}
function safemageClickProductTab() {
    var tab = $$('ul#product_info_tabs li a').first();
    if (typeof(tab) != 'undefined') {
        tab.click();
    }
}
</script>

