<?php 
  /*
  * @copyright   Copyright (c) 2014 www.magebuzz.com
  */
?>     
<?php $_product = Mage::registry('product');?>   
<?php if ($_product->isAvailable()): ?>
  <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
  <?php else: ?>
  <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
  <?php endif; ?>
