<div class="checkout-progress-bar">
    <div class="progressInner addressStep">
        <a href="#!" class="step active" id="addressStep">
            <span class="icon">
                <i class="img"></i>
                <h4><?php echo $this->__('Address') ?></h4>
            </span>
        </a>
        <a href="#!" class="step" id="deliveryStep">
            <span class="icon">
                <i class="img"></i>
                <h4><?php echo $this->__('Providers') ?></h4>
            </span>
        </a>
        <a href="#!" class="step" id="paymentStep">
            <span class="icon">
                <i class="img"></i>
                <h4><?php echo $this->__('Payment') ?></h4>
            </span>
        </a>
        <a href="#!" class="step" id="reviewStep">
            <span class="icon">
                <i class="img"></i>
                <h4><?php echo $this->__('Confirm') ?></h4>
            </span>
        </a>
    </div>
</div>