<?php
/*
NOTICE OF LICENSE

This source file is subject to the SafeMageEULA that is bundled with this package in the file LICENSE.txt.

It is also available at this URL: https://www.safemage.com/LICENSE_EULA.txt

Copyright (c)  SafeMage (https://www.safemage.com/)
*/
?>
<?php

?>
<script type="text/javascript">
safemageSetReadonlyFieldsetChildren('<?php echo $this->getFieldsetId(); ?>');
</script>
