<?php
/*
NOTICE OF LICENSE

This source file is subject to the SafeMageEULA that is bundled with this package in the file LICENSE.txt.

It is also available at this URL: https://www.safemage.com/LICENSE_EULA.txt

Copyright (c)  SafeMage (https://www.safemage.com/)
*/

class SafeMage_Permissions_Model_Config extends SafeMage_Permissions_Model_Abstract
{
    const PERMISSION_EDITABLE = 1;
    const PERMISSION_READONLY = 2;
    const PERMISSION_HIDDEN   = 3;

    protected $_fieldsToEncode = array('store_ids');

    protected $_fieldsToDecode = array('store_ids');

    protected $_attrStrField = 'af';

    protected function _construct()
    {
        $this->_init('safemage_permissions/config');
    }

    public function getGroups()
    {
        $groups = $this->getResource()->getGroups($this->getRoleId());
        return $groups;
    }

    public function getGroup($configId)
    {
        $groups = $this->getGroups();
        $group = isset($groups[$configId]) ? $groups[$configId] : null;
        return $group;
    }

    public function isConfigEditable($configId)
    {
        $group = $this->getGroup($configId);
        $res = ($group['permission'] == self::PERMISSION_EDITABLE);
        return $res;
    }

    public function isConfigReadonly($configId)
    {
        $group = $this->getGroup($configId);
        $res = ($group['permission'] == self::PERMISSION_READONLY);
        return $res;
    }

    public function isConfigHidden($configId)
    {
        $group = $this->getGroup($configId);
        $res = ($group['permission'] == self::PERMISSION_HIDDEN);
        return $res;
    }

	public function getTabsAvailable()
    {		
		return array();
    }

    public function attributesToOptionArray($valueField = 'config_id', $labelField = 'permission')
    {
        $groups = $this->getGroups();
        $a = array();
        foreach($groups as $configId => $data) {
            $id = $data[$valueField];
            $label = $data[$labelField];
            $a[$id]= $label;
        }
        return $a;
    }

    public function attributesToOptionArrayFiltered($valueField = 'config_id', $labelField = 'permission')
    {
        $groups = $this->getGroups();
        $a = array();
        foreach($groups as $configId => $data) {
            if (!$this->_getConfigHelper()->isSystemConfigSectionAllowed($data['section_id'])) {
                continue;
            }

            $id = $data[$valueField];
            $label = $data[$labelField];
            $a[$id]= $label;
        }
        return $a;
    }

    protected function _afterSave()
    {
        $attrStr = $this->getData($this->_attrStrField);

        if ($attrStr) {
            $attrs = Mage::helper('safemage_permissions/request_radio')->decode($attrStr);
            $this->getResource()->update(
                $this->getRoleId(),
                $attrs
            );
        }

        $parent = Mage_Core_Model_Abstract::_afterSave(); // TODO: Change the autogenerated stub
        return $parent;
    }

    protected function _getConfigHelper()
    {
        return Mage::helper('safemage_permissions/config');
    }
}