<?php
/*
NOTICE OF LICENSE

This source file is subject to the SafeMageEULA that is bundled with this package in the file LICENSE.txt.

It is also available at this URL: https://www.safemage.com/LICENSE_EULA.txt

Copyright (c)  SafeMage (https://www.safemage.com/)
*/
?>
<?php
$idGrid = $this->getSelectedProductsGrid()->getId();
$storesSelector1 = "{$idGrid}_product_filter_store_ids";
$storesSelector2 = "product_filter_store_ids";
?>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getCategoryTreeUpdaterVarName(); ?> = new SafeMageCategoryTreeUpdater({
    parameters: <?php echo Mage::helper('safemage_permissions/request')->toRequestParams($this->getCategoryTree()->getData()); ?>,
    url: "<?php echo $this->getCategoryTree()->getLoadTreeHtmlUrl(); ?>",
    idToUpdate: "<?php echo $this->getCategoryTree()->getHtmlId(); ?>",
    idStoreMultiselect: "<?php echo $this->getStoreMultiselectId(); ?>",
    storeIdsVarName: "<?php echo $this->getStoreIdsVarName(); ?>[]",
});

safemageSelectedProductsUpdater = new SafeMageSelectedProductsUpdater({
    storesSelector1: "<?php echo $storesSelector1; ?>",
    storesSelector2: "<?php echo $storesSelector2; ?>",
    productsGridId: "<?php echo $idGrid; ?>",
    productsGridVarName: "<?php echo $idGrid . 'JsObject'; ?>",
    idStoreMultiselect: "<?php echo $this->getStoreMultiselectId(); ?>",
    storeIdsVarName: "<?php echo $this->getStoreIdsVarName(); ?>[]",

    parameters: {},
    url: "<?php echo $this->getUrl('*/*/getRoleProductsSelected', $this->getRequest()->getParams()); ?>",
    idToUpdate: "<?php echo $idGrid; ?>"
});
//]]>
</script>

