<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$_current_category = Mage::registry('current_category');
$categoryName = Mage::getModel('catalog/category')->load($this->getCategoryId())->getName();
$categoryPageTitle = Mage::getModel('catalog/category')->load($this->getCategoryId())->getMetaTitle();
$categoryUrl = Mage::getModel('catalog/category')->load($this->getCategoryId())->getUrl();
$categoryId = Mage::getModel('catalog/category')->load($this->getCategoryId())->getId();
$quote = Mage::getSingleton('checkout/session')->getQuote();
$baseUrl = Mage::getBaseUrl();
?>
<?php if($_productCollection->count()): ?>
    <div class="category-title cate-<?php echo $categoryId;?>">
        <h1><?php echo $categoryPageTitle;?></h1>
        <a class="see-all" href="<?php echo $categoryUrl;?>" title="<?php echo $this->__('See All');?>"><?php echo $this->__('See All');?></a>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            var widthContent = jQuery('.home-product .cate-<?php echo $categoryId;?> > h1').outerWidth();
            var widthParent = jQuery('.home-product .cate-<?php echo $categoryId;?>').outerWidth();
            var margin = (widthParent - widthContent)/2;
            jQuery('.home-product .cate-<?php echo $categoryId;?> > h1').css('margin-left',margin);
        });
    </script>
    <div class="category-products">
        <?php $_collectionSize = $_productCollection->count() ?>
        <ul class="products-grid">
            <?php $i=0; foreach ($_productCollection as $_product): ?>
                <?php $i++;?>
                <?php if($i>6):?>
                    <?php break;?>
                <?php endif;?>
                <li class="item<?php if($i==1):?> first<?php elseif($i==6): ?> last<?php endif; ?>">
                    <div class="item-content">
                        <div class="amlabel-div">
                            <?php // echo Mage::helper('amlabel')->getLabels($_product) ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(143); ?>" width="143" height="143" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>
                        </div>
                        
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> <?php echo Mage::helper('logistic/logistic')->getProductUnitWeightHtml($_product); ?></a></h2>

                        <!-- Show Product_Type case or pallet -->
                        <div>
                            <?php echo Mage::helper('logistic/logistic')->getProductTypeLabel($_product); ?>
                        </div>

                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <div class="actions">
                            <?php if($_product->isSaleable()): ?>
                                <?php $stocklevel = (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty();?>
                                <?php $manageStock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getManageStock();?>
                                <!-- <input type="text" class="input-text input-cart" value="" /> -->
                                <input oninput="maxLengthCheck(this)" type="number" min="0" max="9999" name="qty" id="qty" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty input-cart product-qty-<?php echo $_product->getId(); ?>" />
                                <button data-product-id="<?php echo $_product->getId(); ?>" class="button btn-cart add-cart-button" type="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                    <span class="text"><?php echo $this->__('Add to Order') ?></span>
                                </button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><button title="<?php echo $this->__('Notify me');?>" product_id="<?php echo $_product->getId() ?>" class="button btn-outstock"><span><span><?php echo $this->__('Notify me');?></span></span></button></p>
                            <?php endif; ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
            <script type="text/javascript">decorateGeneric($$('li.item'), ['odd', 'even', 'first', 'last'])</script>
        </ul>
    </div>
<?php endif; ?>
