<?php
$category = $this->getCategory();
$_helper = $this->helper('catalog/output');
$_productCollection = Mage::getModel('catalog/layer')->setCurrentCategory($category)->getProductCollection();
$_productCollection->getSelect()->limit(6);
?>
<div class="list-sub-products">
    <?php if($_productCollection->getSize() > 0):?>
      <?php $_collectionSize = $_productCollection->count() ?>
      <?php $_columnCount = 6; ?>
      <?php $i=0; foreach ($_productCollection as $_product): ?>
      <?php if ($i++%$_columnCount==0): ?>
      <ul class="products-grid col-6">
    <?php endif ?>
      <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> col-md-2 col-sm-2">
        <div class="item-content">
          <div class="amlabel-div">
            <?php // echo Mage::helper('amlabel')->getLabels($_product) ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
              <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(160,190); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <?php if(!$_product->isSaleable()): ?>
              <div class="product-out-stock">
                <span><?php echo $this->__('Out Of Stock');?></span>
              </div>
            <?php endif;?>
          </div>

          <h2 class="product-name 1"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> <?php echo '('.Mage::helper('logistic/logistic')->getProductUnitWeightHtml($_product).')'; ?></a></h2>
          <div class="product-actions">
            <div class="item-price">
              <?php echo $this->getPriceHtml($_product, true).' / Case' ?>
            </div>
            <div class="actions">
              <?php if($_product->isSaleable()): ?>
                <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('More Info')) ?>" class="button btn-cart add-cart-button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="text"><?php echo $this->__('More Info') ?></span></button>
              <?php else: ?>
                <p class="availability out-of-stock"><button title="<?php echo $this->__('Notify me');?>" product_id="<?php echo $_product->getId() ?>" class="button btn-outstock"><span><span><?php echo $this->__('Notify me');?></span></span></button></p>
              <?php endif; ?>
            </div>
          </div>
        </div>
      </li>
      <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
      </ul>
    <?php endif ?>
    <?php endforeach ?>
      <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php else:?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php endif;?>
</div>