<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php 
    $_displayType = $this->getDisplayType();
    $_multiselectEnabled = Mage::helper('amshopby')->getCategoriesMultiselectMode();
    $_showCount = !$this->getData('hide_counts');
    $_maxOptions = max(0, Mage::getStoreConfig('amshopby/general/categories_max_options'));
    if (Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_ADVANCED != $_displayType) {
        $_items = $this->getItems();
        foreach ($_items as $item) {
            if ($item->getIsSelected()) {
                $_maxOptions = 0;
                break;
            }
        }
    }
    $renderedItemsCount = 0;
    $_toggleClasses = ' amshopby-cat-toggle amshopby-cat-toggle-hidden';
?>

<ol <?php if ($this->getCollapsed() && !$this->getHasSelection()) echo 'class="no-display-current"'?>  >
<?php if (in_array($_displayType, array(
            Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_DEFAULT, 
            Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_WSUBCAT,
        ))): ?>
    <?php foreach ($_items as $_item): ?>
        <?php
        $class = 'amshopby-cat amshopby-cat-level-' . max(1, $_item->getLevel());
        if ($_multiselectEnabled) {
            $class .= ' amshopby-cat-multi';
            $class .= ($_item->getIsSelected() ? ' amshopby-cat-multiselected' : '');
        }
        ;
        if ($_maxOptions && $renderedItemsCount++ >= $_maxOptions) {
            $class .= $_toggleClasses;
        }
        ?>
        <li class="<?php echo $class ?>">
            <?php if ($_item->getIsSelected()) :?>
                <?php if ($_multiselectEnabled) echo '<a href="' . $this->urlEscape($_item->getUrl())  .'" data-config = \''. $_item->getApplyData() .' \'>' ?>
                <?php echo $_item->getLabel() ?>
                <?php if ($_showCount && $_item->getCount()):?>
                    <span class="count"><?php echo $_item->getCount() ?></span>
                <?php endif;?>
                <?php if ($_multiselectEnabled) echo '</a>' ?>
            <?php else:?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>" data-config=' <?php echo $_item->getApplyData(); ?>'>
                    <?php echo $_item->getLabel() ?>
                    <?php if ($_showCount && $_item->getCount()):?>
                        <span class="count"><?php echo $_item->getCount() ?></span>
                    <?php endif;?>
                </a>
            <?php endif;?>
        </li>
    <?php endforeach ?>
<?php elseif (Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_STATIC2LVL == $_displayType): ?>
    <?php foreach ($_items as $_item): ?>
        <?php
            $level      = $_item->getLevel();
            $additional = $_item->getIsFolded() ? 'style="display:none"' : '';

            $class      = 'amshopby-cat amshopby-cat-level-' . $level;
            if (1 != $level){
                $class .= ' amshopby-cat-parentid-' . $_item->getParentId();
            } else {
                $renderedItemsCount++;
            }
            if ($_maxOptions && $renderedItemsCount > $_maxOptions) {
                $class .= $_toggleClasses;
            }

            $showIcon = (1 == $level && $_item->getHasChildren());
            $icon = ($_item->getIsChildSelected()) ? 'minus': 'plus';
        ?>
        <li class="<?php echo $class?>" <?php echo $additional?>>
            <?php if ($showIcon): ?><span id="amshopby-cat-id-<?php echo $_item->getId()?>" class="amshopby-plusminus <?php echo $icon?>"></span><?php endif ?>
            <a <?php if ($_item->getIsSelected()):?>class="amshopby-cat-selected"<?php endif?> href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
            <?php if ($_showCount && $_item->getCount()):?>
                <span class="count">(<?php echo $_item->getCount() ?>)</span>
            <?php endif;?>
        </li>
    <?php endforeach ?>
<?php elseif (Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_DROPDOWN == $_displayType): ?>
    <li class="amshopby-category-select">
        <select onchange="if (this.value) window.location.href = value" class="amshopby-select">
            <!-- uncomment to show Filter name in the dropdown <option value=""><?php echo $this->getName() ?></option>-->
            <option value="">&nbsp;</option>
            <?php foreach ($_items as $_item): ?>
            <option  value="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                <?php echo $_item->getLabel() ?>
                <?php if ($_showCount && $_item->getCount()):?>
                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif;?>
            </option>
            <?php endforeach ?>
        </select>
    </li>
    <?php elseif (Amasty_Shopby_Model_Catalog_Layer_Filter_Category::DT_ADVANCED == $_displayType): ?>
        <li class="amshopby-advanced">
            <ol>
                <?php
                $advancedBlock = Mage::getSingleton('core/layout')
                    ->createBlock('amshopby/advanced')
                    ->setToggleClasses($_toggleClasses);
                $advancedBlock->setFilterModel($this->get);
                // Prevent caching like it done in Magento code
                echo $advancedBlock->getHtml();
                $_maxOptions = $advancedBlock->getMaxOptions();
                $renderedItemsCount = $advancedBlock->getRenderedItemsCount();
                ?>
            </ol>
        </li>
		<?php 
		$cat = Mage::registry('current_category')->getId()?Mage::registry('current_category')->getId():'false';
		if( $cat ):
			$category = Mage::getModel('catalog/category')->load(Mage::registry('current_category')->getId()) ?>
			<?php if($category->getLevel() > 1): ?>
				<script type="text/javascript">
					//jQuery(document).ready(function(){
					//	jQuery('#narrow-by-list').addClass('open');
					//	jQuery('.cat-id-<?php echo $cat ?>').closest('li.level0').children('span').click();
					//});
				</script>
			<?php endif ?>
		<?php endif ?>
    <script type="text/javascript">
      jQuery("li.amshopby-cat.parent" ).prepend( "<span class='arrow'>&nbsp;</span>" );
	 jQuery(document).on('click','.back-cate .back-parent', function(){
			  var url = jQuery(this).closest('ol').prev().attr('href');
				url = url.split( '?' )[0];
			  window.location.href = url;
			  jQuery('.col-left #narrow-by-list').removeClass('open-sub');
			  jQuery(".col-left li.parent >ol").hide();
			  jQuery(".col-left li.parent .arrow").removeClass("active");
		  });
		  jQuery("li.parent .arrow").click(function(){
			  if(jQuery(window).width() > 767){
				if(jQuery(this).hasClass("active")){
				  jQuery(this).removeClass("active");
				  jQuery(".col-left li.parent >ol").hide();
				}else{
				  jQuery(".col-left li.parent .arrow").removeClass("active");
				  jQuery(".col-left li.parent >ol").hide();
				  jQuery(this).addClass("active");
				  jQuery(this).next().next().show();
				}
				jQuery('#narrow-by-list').addClass('open-sub');
			  }
			  else{
				  if(jQuery(this).hasClass("active")){
				  jQuery(this).removeClass("active");
				  jQuery(".col-left li.parent >ol").hide();
				}else{
				  jQuery(".col-left li.parent .arrow").removeClass("active");
				  jQuery(".col-left li.parent >ol").hide();
				  jQuery(this).addClass("active");
				  jQuery(this).next().next().show();
				}
				jQuery('#narrow-by-list').addClass('open-sub');
				  /* if(jQuery(this).hasClass("active")){
					  jQuery(this).removeClass("active");
					  jQuery(".col-left li.parent >ol").slideUp('300');
					}else{
					  jQuery(".col-left li.parent .arrow").removeClass("active");
					  jQuery(".col-left li.parent >ol").slideUp('300');
					  jQuery(this).addClass("active");
					  jQuery(this).next().next().slideDown(300);
					} */
			  }
		  });
	  jQuery(document).ready(function(){
		  jQuery('.col-left #narrow-by-list li > a').each(function(e){
			  //console.log(jQuery(this).attr('href'));
			  var url = jQuery(this).attr('href');

				url = url.split( '?' )[0];
				//console.log(url);
				jQuery(this).attr('href', url);
		  });
		/* 	jQuery('.login > a').click(function(e){
				console.log(1234);
				e.preventDefault();
				return false;
			}); */
			/* jQuery('#narrow-by-list li > a').click(function(e){
				e.preventDefault();
				var el = jQuery(this);
				var url = el.attr('href');
				
				jQuery.ajax({
					url: url,
					dataType: 'html',
					type : 'post',
					success: function(data){ 
						//console.log(jQuery('title', data).text());
						window.history.pushState({href: url}, '', url);
						var content = jQuery('.col-main', data).html();
						jQuery('.col-main').html(content);
						if(jQuery(el).parent().hasClass('parent')){
							jQuery(el).prev().click();
						}
						//document.title = jQuery('title', data).text();
						//console.log(data);
					},
					error: function(){
					  console.log('error');
					}
				});
				return false;
			}); */
			
		});
    </script>
    <?php endif ?>
<?php
    $add = $renderedItemsCount - $_maxOptions;
    if ($add > 0 && $_maxOptions > 0) {
        $text = sprintf($this->__('View %d More'), $add);
        echo '<li class="amshopby-clearer"><a id="amshopby-category-more" href="#">' . $text . '</a></li>';
        echo '<li class="amshopby-clearer"><a id="amshopby-category-less" href="#" style="display:none">' . $this->__('Show Less') . '</a></li>';
    }
?>
</ol>
