<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php $helper = Mage::helper('amshopby'); ?>
<?php
$custom = Mage::getStoreConfig('amastycustom/general/enable');
$csHelper= Mage::helper('amastycustom');
?>
<div class="block cat-image">
</div>
<?php if( ($custom == 1 && $csHelper->isExtraTabsRunning() ) || $this->canShowBlock()): ?> 
    <div class="block block-layered-nav">
        <!--<div class="block-title">
            <strong><span><?php /*echo $this->__('Shop By') */?></span></strong>
        </div>-->
        <div class="block-content">
            <?php echo $this->getStateHtml() ?>
            <?php if ($this->getLayer()->getState()->getFilters() && method_exists('Mage', 'getEdition')): // CE 1.7+, EE 1.12+?>
                <div class="actions"><a href="<?php echo Mage::helper('amshopby/url')->getFullUrl(array(), 1) ?>">
                        <?php echo Mage::helper('catalog')->__('Clear All') ?></a>
                </div>
            <?php endif; ?>
            <?php if( ($custom == 1 && $csHelper->isExtraTabsRunning() ) || $this->canShowOptions()): ?>
                <div class="amshopby-container-top block-layered-nav">
                  <div class="tabs-title tabs-title-style1">
                  <?php $i=0; foreach ($this->getFilters() as $_filter): ?>
                  <?php if($_filter->getItemsCount()): $i++;?>
                    <?php  $position = Mage::helper('amshopby')->getAttributePosition($_filter); ?>
                      <div id="<?php echo $_filter->getAttributeModel()->getAttributeCode(); ?>" onclick="showcontent(this)" class="tab-title <?php if($i==1):?>active<?php endif; ?>">
                        <span><?php echo $this->__($_filter->getName()) ?></span>
                      </div>
                    <?php endif; ?>
                  <?php endforeach; ?>
                  </div>
                    <?php $i=0;foreach ($this->getFilters() as $_filter): ?>
                        <?php if($_filter->getItemsCount()): $i++; ?>
                            <?php  $position = Mage::helper('amshopby')->getAttributePosition($_filter); ?>
                            <div id="tab-content-<?php echo $_filter->getAttributeModel()->getAttributeCode(); ?>" class="amshopby-item-top am-toggle-content tab-content <?php if($i==1):?>active<?php endif; ?>">
                                <?php if($_filter->getAttributeModel()->getAttributeCode() == "brands"): ?>
                                    <dl id="narrow-by-list" class="amshopby-narrow-by-list" data-position="<?php echo $position;?>">
                                        <dt><?php echo $this->__($_filter->getName()) ?></dt>
                                        <dd style="background:none"><?php echo $_filter->getHtml() ?></dd>
                                    </dl>
                                    <script>
                                        jQuery( document ).ready(function() {
                                            console.log( "ready!" );
                                            jQuery('.owl-carousel-brand').owlCarousel({
                                                loop:true,
                                                center: true,
                                                margin:10,
                                                navigation: true,
                                                pagination: false,
                                                rewindNav: false,
                                                navigationText: ["prev","next"]
                                            })
                                        });
                                    </script>
                                <?php else: ?>
                                    <dl id="narrow-by-list" class="amshopby-narrow-by-list" data-position="<?php echo $position;?>">
                                        <?php if ($_filter->getAttributeCode() == 'price') : ?>
                                            <?php $_filter->addData(array('amprice-position' => 'top')); ?>
                                        <?php endif; ?>
                                        <dt><?php echo $this->__($_filter->getName()) ?></dt>
                                        <dd style="background:none"><?php echo $_filter->getHtml() ?></dd>
                                    </dl>
                                <?php endif;?>
                            </div>
                          <script type="text/javascript">
                            jQuery('tab-content-<?php echo $_filter->getAttributeModel()->getAttributeCode(); ?>').mCustomScrollbar();
                          </script>
                        <?php endif; ?>
                    <?php endforeach; ?> 
					<?php if ( $custom == 1): ?>
						<div class="fillter-products">
							<div class="tabs-title-second tabs-title-style1">
								<div id="am_all"
									 onclick="ajaxgetcontent('<?php echo $csHelper->addCurrentUrlParam("amf=all");?>','am_all')"
									 class="tab-title-second tab-title<?php if($csHelper->getCurrentExtraTabs() == "all") echo " "."active";?>">
									<span><?php echo $this->__('All') ?></span>
								</div>
								<div id="am_new"
									 onclick="ajaxgetcontent('<?php echo $csHelper->addCurrentUrlParam("amf=new");?>','am_new')"
									 class="tab-title-second tab-title<?php if($csHelper->getCurrentExtraTabs() == "new") echo " "."active";?>">
									<span><?php echo $this->__('New') ?></span>
								</div>
								<div id="am_onsale"
									 onclick="ajaxgetcontent('<?php echo $csHelper->addCurrentUrlParam("amf=sale");?>','am_onsale')"
									 class="tab-title-second tab-title<?php if($csHelper->getCurrentExtraTabs() == "sale") echo " "."active";?>">
									<span><?php echo $this->__('On Sale') ?></span>
								</div>
								<div id="am_instock"
									 onclick="ajaxgetcontent('<?php echo $csHelper->addCurrentUrlParam("amf=instock");?>','am_instock')"
									 class="tab-title-second tab-title<?php if($csHelper->getCurrentExtraTabs() == "instock") echo " "."active";?>">
									<span><?php echo $this->__('In Stock') ?></span>
								</div>
								<div class="tb-copy">
								
								</div>
							</div> 							
						</div>						
					<?php endif;?>
                </div>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
                <script type="text/javascript">

                    function showcontent(elm){
                      var id = elm.getAttribute('id');
                      jQuery('.tab-title').removeClass('active');
                      jQuery('.tab-content').removeClass('active');
                      jQuery('#'+id).addClass('active');
                      jQuery('#tab-content-'+id).addClass('active');
                    }
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php else: ?>
    <div style="display:none" class="<?php echo $this->getBlockId()?>"></div>
<?php endif; ?>

<?php  if($helper->isNeedAjax()): ?>
    <script>
        window.amshopby_scroll_to_products = <?php echo $helper->isAjaxScrollEnabled() ? 'true' : 'false'; ?> ;
    </script>
<?php endif; ?>
