<?php
/**
 * Magebuzz 2015
 */
?>
<?php
$_item = $this->getItem();
$_product = $_item->getProduct();
$_productId = $_product->getId();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
$qty = $this->getQty();
$price = $_product->getPrice();
$specialPrice = $_product->getSpecialPrice();
$totalPrice = $qty * $price;
if($specialPrice){
  $totalPrice = $qty * $specialPrice;
}
?>
<li class="item" data-product-id="<?php echo $_productId;?>">
  <div class="item-left">
    <div class="item-image">
      <?php if ($this->hasProductUrl()): ?>
        <a href="<?php echo $this->getProductUrl()?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(40, 60)->setWatermarkSize('30x10'); ?>" width="40" height="60" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></a>
      <?php else: ?>
        <span class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(78, 107)->setWatermarkSize('30x10'); ?>" width="78" height="107" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></span>
      <?php endif; ?>
    </div>
    <div class="product-details">
      <div class="product-info">
        <p class="product-name">
          <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?>&nbsp;<span><?php echo Mage::helper('logistic/logistic')->getProductUnitWeightHtml($_product); ?></span></a>
        </p>
        <p class="product-type"><?php echo $this->__('Type : ');?><?php echo Mage::helper('logistic/logistic')->getProductType($_product); ?></p>
      </div>
      <?php if ($_options = $this->getOptionList()):?>
      <div class="truncated">
        <div class="truncated_full_value">
          <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
            <dd>
              <?php if (is_array($_option['value'])): ?>
                <?php echo nl2br(implode("\n", $_option['value'])) ?>
              <?php else: ?>
                <?php echo $_option['value'] ?>
              <?php endif; ?>
            </dd>
            <?php endforeach; ?>
          </dl>
        </div>
        <a href="#" onclick="return false;" class="details"><?php echo $this->__('Details') ?></a>
      </div>
      <?php endif; ?>
    </div>
  </div>
  <div class="item-right">
    <div class="price-box <?php if($specialPrice):?>is-special<?php endif;?>">
      <?php if ($canApplyMsrp): ?>
        <span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>
      <?php else: ?>
      <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
          <?php echo $this->__('Excl. Tax'); ?>:
        <?php endif; ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
          <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
        <?php else: ?>
          <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
        <?php endif; ?>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
          <br />
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
          <small>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
              <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
            <?php endforeach; ?>
          </small>
        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
          <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
          <?php endforeach; ?>
        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
        <small>
          <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
          <?php endforeach; ?>
        </small>
        <?php endif; ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
          <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
        <?php endif; ?>
      <?php endif; ?>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
      <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
      <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <br /><?php echo $this->__('Incl. Tax'); ?>:
      <?php endif; ?>
      <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
        <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
      <?php else: ?>
        <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
      <?php endif; ?>
      <?php if (Mage::helper('weee')->getApplied($_item)): ?>
        <br />
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
        <small>
          <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
        <?php endforeach; ?>
      </small>
      <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
          <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span>
        <?php endforeach; ?>
      <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
        <small>
          <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
          <?php endforeach; ?>
      </small>
      <?php endif; ?>
      <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
        <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
      <?php endif; ?>
    <?php endif; ?>
    <?php endif; ?>
    <?php endif; //Can apply MSRP ?>
    <?php if($specialPrice):?>
      <p class="old-price">
        <span class="price"><?php echo Mage::helper('core')->currency($price,true,false); ?></span>
      </p>
    <?php endif;?>
    </div>
    <div class="item-qty">
      <!-- <a class="qty-inc" item_id="<?php echo $_item->getId() ?>" title="<?php echo $this->__('Increased product');?>" href="javascript:void(0);" data-product-id="<?php echo $_productId;?>"></a>
      <input disabled="disabled" item_id="<?php echo $_item->getId() ?>" class="qty cart-qty" name="" value="<?php echo $this->getQty()?>"/>
      <a class="qty-des" item_id="<?php echo $_item->getId() ?>" title="<?php echo $this->__('Reduced product');?>" href="javascript:void(0);" data-product-id="<?php echo $_productId;?>"></a> -->
      <input
      id="qinput-<?php echo $_item->getId(); ?>"
      data-link="<?php echo $this->getAjaxUpdateUrl() ?>"
      data-item-id="<?php echo $_item->getId(); ?>"
      data-cart-item-id="<?php echo $_item->getSku(); ?>"
      class="qty cart-item-quantity input-text" name=""
      value="<?php echo $this->getQty()?>"
      <?php if ($this->isOnCheckoutPage()) echo 'disabled'; ?>
      />
    </div>
    <div class="total-price">
       <div class="item-subtotal-<?php echo $_item->getId() ?>">
        <span class="price"><?php echo Mage::helper('core')->currency($_item->getRowTotalInclTax(),true,false); ?></span>
      </div>
    </div>
    <div class="actions">
      <div class="btn-remove-minicart-item" item_id="<?php echo $_item->getId() ?>" title="<?php echo $this->__('Remove This Item') ?>" data-product-id="<?php echo $_productId;?>"><i class="fa fa-times" aria-hidden="true"></i></div>
    </div>
  </div>
</li>