<?php
$lastLoginDateAdmin = $this->getLastLoginDate();
$lastLoginDateStore = $this->getStoreLastLoginDate();

$createDateAdmin    = $this->getCreateDate();
$createDateStore    = $this->getStoreCreateDate();
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('customer')->__('Personal Information') ?></h4></div>
    <fieldset>
        <table cellspacing="2" class="box-left">
            <tr>
                <td><strong><?php echo $this->__('Email:') ?></strong></td>
                <td><a target="_blank" href="<?php echo $this->getUrl('adminhtml/customer/edit', array('id' => $this->getCustomer()->getId())); ?>"><?php echo $this->getCustomer()->getemail(); ?></a></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Last Logged In:') ?></strong></td>
                <td><?php echo $lastLoginDateAdmin ?> (<?php echo $this->getCurrentStatus() ?>)</td>
            </tr>
            <?php if ($lastLoginDateAdmin != $lastLoginDateStore): ?>
                <tr>
                    <td><strong><?php echo $this->__('Last Logged In (%s):', $this->getStoreLastLoginDateTimezone()) ?></strong></td>
                    <td><?php echo $lastLoginDateStore ?> (<?php echo $this->getCurrentStatus() ?>)</td>
                </tr>
            <?php endif; ?>
            <tr>
                <td><strong><?php echo $this->__('Confirmed email:') ?></strong></td>
                <td><?php echo $this->getIsConfirmedStatus() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Account Created on:') ?></strong></td>
                <td><?php echo $createDateAdmin ?></td>
            </tr>
            <?php if ($createDateAdmin != $createDateStore): ?>
                <tr>
                    <td><strong><?php echo $this->__('Account Created on (%s):', $this->getStoreCreateDateTimezone()) ?></strong></td>
                    <td><?php echo $createDateStore ?></td>
                </tr>
            <?php endif; ?>
            <tr>
                <td><strong><?php echo $this->__('Account Created in:') ?></strong></td>
                <td><?php echo $this->getCreatedInStore() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Customer Group:') ?></strong></td>
                <td><?php echo $this->getGroupName() ?></td>
            </tr>
        </table>
        <address class="box-right">
            <strong><?php echo $this->__('Default Billing Address') ?></strong><br/>
            <?php echo $this->getBillingAddressHtml() ?>
        </address>
    </fieldset>
</div>


<?php

    $block = $this->getLayout()->createBlock('adminhtml/Customer_Edit_Tab_View_Sales');
    $block->setTemplate('customer/tab/view/sales.phtml');
    echo $block->toHtml();
?>

<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="icon-head head-customer-view">Orders</h4></div>
    <fieldset>
        <?php
            echo $this->getLayout()->createBlock('Quotation/Adminhtml_Edit_Tabs_Orders')->toHtml();
        ?>
    </fieldset>
</div>

<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="icon-head head-customer-view">Other quotes</h4></div>
    <fieldset>
        <?php
        echo $this->getLayout()->createBlock('Quotation/Adminhtml_Edit_Tabs_Quotes')->toHtml();
        ?>
    </fieldset>
</div>
