<div class="checkout-progress-bar">
    <div class="progressInner addressStep">
        <a href="#!" class="step active" id="addressStep">
            <span class="icon">
                <i class="img"></i>
                <label><span>1</span></label>
                <h4>Select Address</h4>
            </span>
            <span class="bar">
                <span class="progress"></span>
            </span>
        </a>

        <a href="#!" class="step" id="deliveryStep">
            <span class="icon">
                <i class="img"></i>
                <label><span>2</span></label>
                <h4>Select Freight</h4>
            </span>
            <span class="bar">
                <span class="progress"></span>
            </span>
        </a>

        <a href="#!" class="step" id="paymentStep">
            <span class="icon">
                <i class="img"></i>
                <label><span>3</span></label>
                <h4>Select Payment</h4>
            </span>
            <span class="bar">
                <span class="progress"></span>
            </span>
        </a>

        <a href="#!" class="step" id="reviewStep">
            <span class="icon">
                <i class="img"></i>
                <label><span>4</span></label>
                <h4>Review & Confirm</h4>
            </span>
            <span class="bar">
                <span class="progress"></span>
            </span>
        </a>
    </div>
</div>