<script type="text/javascript">
    <?php if (Mage::getStoreConfig('ajaxcart/general/enabled')): ?>
    document.observe("dom:loaded", function() {
        ajaxCart = new AjaxCart(
            {
                'show_success_message': <?php echo Mage::getStoreConfig('ajaxcart/general/display_success_message'); ?>,
                'timerErrorMessage': 3000,
                'addWishlistItemUrl': '<?php echo Mage::getUrl('ajaxcart/index/addWishlistItem');?>',
                'updateItemUrl': '<?php echo Mage::getUrl('ajaxcart/index/ajaxUpdate');?>',
                'inShoppingCart': <?php echo strpos(Mage::app()->getRequest()->getPathInfo(),'checkout/cart') === false ? 'false' : 'true';?>,
                'isValidCustomer': <?php echo $this->isValidCustomer(); ?>,
                'updateMinicartUrl': '<?php echo Mage::getUrl('ajaxcart/index/updateMinicart');?>'
            }
        );
    });
    <?php endif; ?>
</script>